(function(){
  'use strict';
  var URL='http://127.0.0.1:19999/translate';
  var BATCH_URL='http://127.0.0.1:19999/batch';
  var PREFETCH_URL='http://127.0.0.1:19999/prefetch';
  var CACHE_LOOKUP_URL='http://127.0.0.1:19999/cache/lookup';
  var CJK_FONT='DeepSeekCJK';
  var MAX_RUNTIME_CACHE=4096;
  var MAX_RETRY_COOLDOWNS=4096;
  var MAX_LOCAL_LOOKUP_KEYS=4096;
  // 有界键状态把容量、淘汰顺序和数组压缩收拢在一个深 Module 内。顺序队列只移动 head，
  // 达到阈值才线性压缩；版本号可识别删除后重插的同名键，避免旧队列槽误删新值。
  function createBoundedKeyState(limit,onEvict){var values=Object.create(null),versions=Object.create(null),order=[],head=0,count=0,sequence=0,owns=Object.prototype.hasOwnProperty; limit=Math.max(1,Number(limit)||1); function has(key){return owns.call(values,key);} function compact(force){if(!force&&head<256&&order.length<=limit*2) return; var next=[]; for(var i=head;i<order.length;i++){var entry=order[i]; if(versions[entry.key]===entry.version) next.push(entry);} order=next; head=0;} function trim(){while(count>limit&&head<order.length){var entry=order[head++]; if(versions[entry.key]!==entry.version) continue; delete versions[entry.key]; delete values[entry.key]; count--; if(onEvict) onEvict(entry.key);} compact(false);} return {has:has,get:function(key){return has(key)?values[key]:undefined;},put:function(key,value){key=String(key); if(!has(key)) count++; sequence++; versions[key]=sequence; values[key]=value; order.push({key:key,version:sequence}); trim(); compact(false); return value;},remove:function(key){if(!has(key)) return false; delete values[key]; delete versions[key]; count--; compact(false); return true;},size:function(){return count;}};}
  var cache=createBoundedKeyState(MAX_RUNTIME_CACHE,function(key){if(typeof localLookupState!=='undefined'&&localLookupState&&!localLookupPending[key]) localLookupState.remove(key); if(typeof retryAfter!=='undefined'&&retryAfter) retryAfter.remove(key);});
  var pending=Object.create(null);
  var pendingCount=0;
  var retryAfter=createBoundedKeyState(MAX_RETRY_COOLDOWNS);
  var MISS_RETRY_MS=1000;
  var MAX_PENDING=64;
  var MESSAGE_PAGE_BATCH_MAX=32;
  var MESSAGE_PAGE_CHAR_BUDGET=6000;
  var MAX_MESSAGE_PAGE_PRIME=192;
  var MAX_QUEST_PRIME=128;
  var messagePagePending=Object.create(null);
  var suppressLookupRequests=0;
  var localLookupState=createBoundedKeyState(MAX_LOCAL_LOOKUP_KEYS);
  var localLookupPending=Object.create(null);
  var ACTIVE_MESSAGE_POLL_INITIAL_MS=40;
  var ACTIVE_MESSAGE_POLL_MAX_MS=1000;
  var ACTIVE_MESSAGE_POLL_WINDOW_MS=15000;
  var activeMessagePoll={win:null,signature:'',deadline:0,delay:0,timer:false,generation:0};
  var rpgmErrorCounts=Object.create(null);
  // 兼容性降级只覆盖无法从上游修复的可选插件或渲染器 API。
  // 降级绝不会把失败翻译变成成功：每次故障都会计数并记录；如果诊断控制台
  // 不存在，则重新抛出异常而不是隐藏原始错误。
  function reportRpgmError(context,error){var e=error instanceof Error?error:new Error(String(error)); var key=String(context||'unknown')+':'+(e.name||'Error'); var count=(rpgmErrorCounts[key]||0)+1; rpgmErrorCounts[key]=count; if(count<=3||(count&(count-1))===0){var detail=count===1&&(e.stack||e.message)?(e.stack||e.message):e.message; if(window.console&&typeof console.error==='function'){console.error('[DeepSeek RPGM] '+context+' failed #'+count+': '+detail);}else{throw e;}}}
  // NW.js 把游戏暴露为 chrome-extension 页面。新版 Chromium 可能让 localhost XHR
  // 卡在私有网络/CORS 边界而不触发渲染器回调，但同一游戏进程中的内嵌 Node
  // 传输仍可用。该问题无法在上游游戏或插件代码中修复。Node 失败后回退到异步 XHR，
  // 通过 reportRpgmError 报告并返回状态 0/原文，绝不会产生缓存成功项。
  function rpgmEndpointPath(endpoint){var match=/^https?:\/\/[^/]+(\/.*)$/.exec(String(endpoint||'')); return match?match[1]:'/';}
  function sendRpgmJson(endpoint,payload,timeoutMs,context,callback){var body=JSON.stringify(payload),nodeRuntime=false; try{nodeRuntime=typeof require==='function'&&typeof process==='object'&&process.versions&&!!process.versions.nw; if(nodeRuntime){var http=require('http'),completed=false; function complete(response,eventName){if(completed) return; completed=true; callback(response,eventName);} var req=http.request({hostname:'127.0.0.1',port:19999,path:rpgmEndpointPath(endpoint),method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body,'utf8')}},function(res){var responseText='',oversized=false; res.setEncoding('utf8'); res.on('data',function(chunk){if(oversized) return; responseText+=chunk; if(responseText.length>8388608){oversized=true; req.destroy(new Error('response exceeds 8 MiB'));}}); res.on('end',function(){if(!oversized) complete({status:Number(res.statusCode)||0,responseText:responseText},'node-http');}); res.on('error',function(error){reportRpgmError('node-http-response-'+String(context||'request'),error); complete({status:0,responseText:''},'node-response-error');});}); req.setTimeout(Number(timeoutMs)||12000,function(){req.destroy(new Error('timeout'));}); req.on('error',function(error){reportRpgmError('node-http-'+String(context||'request'),error); complete({status:0,responseText:''},error&&error.message==='timeout'?'timeout':'node-error');}); req.end(body); return;}}catch(e){reportRpgmError('start-node-http-'+String(context||'request'),e);} var x=null,done=false; function finish(eventName){if(done) return; done=true; callback(x,eventName);} try{x=new XMLHttpRequest(); x.open('POST',endpoint,true); x.timeout=Number(timeoutMs)||12000; x.setRequestHeader('Content-Type','application/json'); x.onreadystatechange=function(){if(x.readyState===4) finish('readystatechange');}; x.onload=function(){finish('load');}; x.onerror=function(){finish('error');}; x.ontimeout=function(){finish('timeout');}; x.send(body);}catch(e){reportRpgmError('start-xhr-'+String(context||'request'),e); finish('constructor');}}
  function installCjkFont(){
    try{if(!installCjkFont._dsCssInjected){var st=document.createElement('style'); st.type='text/css'; st.textContent="@font-face{font-family:'DeepSeekCJK';src:url('fonts/ds_font.ttf') format('truetype'),url('fonts/ds_font.ttc') format('truetype');font-weight:normal;font-style:normal;} body,canvas{font-family:'DeepSeekCJK',sans-serif;}"; (document.head||document.documentElement).appendChild(st); installCjkFont._dsCssInjected=true; if(document.fonts&&document.fonts.load){document.fonts.load('16px '+CJK_FONT);}}}
    catch(e){reportRpgmError('install-css-font',e);}
    try{if(window.Window_Base&&Window_Base.prototype.standardFontFace&&!Window_Base.prototype._dsStandardFontFace){var oldFont=Window_Base.prototype.standardFontFace; Window_Base.prototype._dsStandardFontFace=oldFont; Window_Base.prototype.standardFontFace=function(){var base=oldFont.call(this)||''; return base.indexOf(CJK_FONT)>=0?base:(base?CJK_FONT+', '+base:CJK_FONT);};}}
    catch(e){reportRpgmError('install-mv-font-face',e);}
    try{if(window.Game_System&&Game_System.prototype.mainFontFace&&!Game_System.prototype._dsMainFontFace){var oldMain=Game_System.prototype.mainFontFace; Game_System.prototype._dsMainFontFace=oldMain; Game_System.prototype.mainFontFace=function(){var base=oldMain.call(this)||''; return base.indexOf(CJK_FONT)>=0?base:(base?CJK_FONT+', '+base:CJK_FONT);};}}
    catch(e){reportRpgmError('install-mz-font-face',e);}
  }
  installCjkFont();
  function hasCjk(s){return /[\u4e00-\u9fff\u3000-\u303f\uff00-\uffef]/.test(String(s||''));}
  function keyOf(s){return String(s==null?'':s).replace(/^[ \t\r\n]+|[ \t\r\n]+$/g,'');}
  function isLayoutOnly(s){var t=String(s==null?'':s); t=t.replace(/(?:<WordWrap>|<br\s*\/?>)/gi,''); t=t.replace(/\\(?:c|i|fs|fr|fb|fi|oc|ow|v|n[1-5]?|nc|nr|nd[1-5]?|ndc|ndr|nt[1-5]?|ntc|ntr)(?:\[[^\]]{0,64}\]|<[^>\n]{0,64}>)/gi,''); t=t.replace(/\\[{}$.|!><^]/g,''); return !/[A-Za-z\u0080-\uffff]/.test(t);}
  function rpgmControlTokens(s){return String(s==null?'':s).match(/(?:<WordWrap>|<br\s*\/?>|\\(?:c|i|fs|fr|fb|fi|oc|ow|v|n[1-5]?|nc|nr|nd[1-5]?|ndc|ndr|nt[1-5]?|ntc|ntr)(?:\[[^\]]{0,64}\]|<[^>\n]{0,64}>))/gi)||[];}
  function rpgmLatinWords(s){var t=String(s==null?'':s); t=t.replace(/(?:<WordWrap>|<br\s*\/?>|\\(?:c|i|fs|fr|fb|fi|oc|ow|v|n[1-5]?|nc|nr|nd[1-5]?|ndc|ndr|nt[1-5]?|ntc|ntr)(?:\[[^\]]{0,64}\]|<[^>\n]{0,64}>))/gi,' '); return t.toLowerCase().match(/[a-z][a-z'-]{2,}/g)||[];}
  function hasSuspiciousRpgmSourceResidue(src,out){if(!hasCjk(out)) return false; var a=rpgmLatinWords(src),b=rpgmLatinWords(out); if(a.length<4||b.length<3) return false; for(var i=0;i+2<a.length;i++){for(var j=0;j+2<b.length;j++){if(a[i]===b[j]&&a[i+1]===b[j+1]&&a[i+2]===b[j+2]) return true;}} return false;}
  function safeRpgmTranslation(src,out){src=String(src==null?'':src); out=String(out==null?'':out); if(!out||out===src) return out||src; var a=rpgmControlTokens(src),b=rpgmControlTokens(out); if(a.length!==b.length) return src; for(var i=0;i<a.length;i++){if(String(a[i]).toLowerCase()!==String(b[i]).toLowerCase()) return src;} if(hasSuspiciousRpgmSourceResidue(src,out)) return src; return out;}
  function cacheSafeRpgmTranslation(key,value,context){var residue=hasSuspiciousRpgmSourceResidue(key,value),safe=safeRpgmTranslation(key,value); if(safe&&safe!==key){cache.put(key,safe); retryAfter.remove(key); return true;} if(value&&value!==key) reportRpgmLayoutFallback(residue?'mixed-language-guard':(context||'cache-control-guard'),'cache result rejected'); return false;}
  function markRpgmDisplayTarget(target,text){try{var key=keyOf(text); if(!target||!key||hasCjk(key)||!/[A-Za-z]/.test(key)) return; target._dsRpgmTranslationTarget=true; if(target.contents) target.contents._dsRpgmTranslationTarget=true;}catch(e){reportRpgmError('mark-display-target',e);}}
  function canAutoRefreshWindow(root){if(!root||root.visible===false||root._destroyed||root._closing) return false; if(typeof root.openness==='number'&&root.openness<=0&&!root._opening) return false; if(root.contents&&root.contents._destroyed) return false; return !!(root._dsRpgmTranslationTarget||(root.contents&&root.contents._dsRpgmTranslationTarget));}
  function isPersistenceScene(scene){try{if(!scene) return false; if(window.Scene_File&&scene instanceof Scene_File) return true; var mode=typeof scene.mode==='function'?scene.mode():scene._mode; return mode==='save'||mode==='load';}catch(e){reportRpgmError('detect-persistence-scene',e); return false;}}
  var refreshQueued=false;
  function messageRenderSignature(source,translated){return source.join('\u001e')+'\u001f'+translated.join('\u001e');}
  function activeMessageSourceSignature(lines){var out=[]; for(var i=0;i<lines.length;i++) out.push(String(lines[i]==null?'':lines[i])); return out.join('\u001e');}
  function stopActiveMessageCachePoll(win){if(win&&activeMessagePoll.win!==win) return; activeMessagePoll.win=null; activeMessagePoll.signature=''; activeMessagePoll.deadline=0; activeMessagePoll.delay=0; activeMessagePoll.timer=false; activeMessagePoll.generation++;}
  // 本地服务会刻意立即返回 queued 原文，稍后才完成远程翻译，因此渲染器没有
  // 可从上游订阅的完成回调。同一原文页仍可见时，只按有界退避轮询 /cache/lookup。
  // 未命中绝不会变成缓存成功；页面变化会取消当前代，超时则记录诊断。
  function scheduleActiveMessageCachePoll(win,lines){try{if(!win||!win._textState||win.visible===false||win._destroyed||win._closing||!lines||!lines.length) return; var signature=activeMessageSourceSignature(lines),now=Date.now(); if(activeMessagePoll.win!==win||activeMessagePoll.signature!==signature){activeMessagePoll.win=win; activeMessagePoll.signature=signature; activeMessagePoll.deadline=now+ACTIVE_MESSAGE_POLL_WINDOW_MS; activeMessagePoll.delay=ACTIVE_MESSAGE_POLL_INITIAL_MS; activeMessagePoll.timer=false; activeMessagePoll.generation++;} if(now>=activeMessagePoll.deadline){reportRpgmError('active-message-cache-poll-timeout',new Error('translation stayed unresolved for visible message page')); stopActiveMessageCachePoll(win); return;} if(activeMessagePoll.timer) return; activeMessagePoll.timer=true; var generation=activeMessagePoll.generation,delay=activeMessagePoll.delay; setTimeout(function(){try{if(generation!==activeMessagePoll.generation) return; activeMessagePoll.timer=false; var gm=window.$gameMessage,current=gm&&gm._texts; if(activeMessagePoll.win!==win||!current||!Array.isArray(current)||activeMessageSourceSignature(current)!==signature||!win._textState||win.visible===false||win._destroyed||win._closing){stopActiveMessageCachePoll(win); return;} var plan=planMessagePage(current),keys=[plan.joined].concat(plan.candidates,plan.liveCandidates),seen=Object.create(null),lookupKeys=[]; for(var i=0;i<keys.length;i++){var key=keyOf(keys[i]); if(!key||seen[key]||hasCjk(key)||isLayoutOnly(key)) continue; seen[key]=true; if(!localLookupPending[key]) localLookupState.remove(key); lookupKeys.push(key);} activeMessagePoll.delay=Math.min(ACTIVE_MESSAGE_POLL_MAX_MS,Math.max(ACTIVE_MESSAGE_POLL_INITIAL_MS,delay*2)); if(!requestLocalCacheKeys(lookupKeys,512)) scheduleActiveMessageCachePoll(win,current);}catch(e){reportRpgmError('run-active-message-cache-poll',e); stopActiveMessageCachePoll(win);}},delay);}catch(e){reportRpgmError('schedule-active-message-cache-poll',e); stopActiveMessageCachePoll(win);}}
  function refreshActiveRpgmMessage(win){try{var gm=window.$gameMessage,original=gm&&gm._texts; if(!win||win.visible===false||win._destroyed||win._closing) return; if(!original||!Array.isArray(original)||!original.length){win._dsRpgmDeferredMessageStart=false; stopActiveMessageCachePoll(win); return;} if(typeof win.openness==='number'&&win.openness<=0&&!win._opening) return; if(!win._textState){if(win._dsRpgmDeferredMessageStart&&typeof win.startMessage==='function'){win._dsRpgmDeferredMessageStart=false; win.startMessage();} return;} var translated=translateMessageLines(original,true); if(!translated||sameRpgmTextArray(original,translated)){scheduleActiveMessageCachePoll(win,original); return;} stopActiveMessageCachePoll(win); var signature=messageRenderSignature(original,translated); if(win._dsRpgmRenderedMessageSignature===signature) return; win._dsRpgmRenderedMessageSignature=signature; if(typeof win.startMessage==='function') win.startMessage();}catch(e){reportRpgmError('refresh-active-message',e);}}
  var sceneWalkGeneration=0;
  function createSceneWalkSeen(){sceneWalkGeneration=(sceneWalkGeneration+1)%2147483647||1; return {set:typeof Set==='function'?new Set():null,generation:sceneWalkGeneration,fallback:[]};}
  // 老 NW.js 缺少 Set 时使用对象代际标记，避免每个节点都线性搜索。若第三方冻结对象拒绝写标记，
  // 该限制无法从游戏 hook 上游修复；只为该对象退回有界数组去重，可能变慢但不会伪造翻译成功，
  // 并由 scene-walk-marker-fallback 记录限频诊断。
  function enterSceneWalk(root,seen){if(seen.set){if(seen.set.has(root)) return false; seen.set.add(root); return true;} try{if(root._dsRpgmRefreshGeneration===seen.generation) return false; root._dsRpgmRefreshGeneration=seen.generation; if(root._dsRpgmRefreshGeneration===seen.generation) return true; throw new Error('generation marker rejected');}catch(e){reportRpgmError('scene-walk-marker-fallback',e); for(var i=0;i<seen.fallback.length;i++){if(seen.fallback[i]===root) return false;} seen.fallback.push(root); return true;}}
  function walkSceneWindows(root,seen,state){if(!root||state.count>=2048||!enterSceneWalk(root,seen)) return; state.count++; try{if(window.Window_Message&&root instanceof Window_Message) refreshActiveRpgmMessage(root); else if(canAutoRefreshWindow(root)&&typeof root.refresh==='function') root.refresh();}catch(e){reportRpgmError('refresh-rendered-window',e);} var children=root.children; if(children&&children.length){for(var i=0;i<children.length;i++) walkSceneWindows(children[i],seen,state);}}
  function walkSceneOwnedWindows(scene,seen,state){var names; try{names=Object.keys(scene||{});}catch(e){reportRpgmError('list-scene-owned-windows',e); return;} for(var i=0;i<names.length&&state.count<2048;i++){var name=names[i]; if(!/window/i.test(name)) continue; try{var owned=scene[name]; if(owned&&typeof owned==='object') walkSceneWindows(owned,seen,state);}catch(e){reportRpgmError('read-scene-owned-window',e);}}}
  function runWindowRefresh(){try{var scene=window.SceneManager&&SceneManager._scene; if(scene&&!isPersistenceScene(scene)){var seen=createSceneWalkSeen(),state={count:0}; walkSceneWindows(scene,seen,state); walkSceneOwnedWindows(scene,seen,state);}}catch(e){reportRpgmError('refresh-scene-windows',e);}finally{refreshQueued=false;}}
  function requestWindowRefresh(){if(refreshQueued) return; refreshQueued=true; try{if(window.setTimeout){setTimeout(runWindowRefresh,0); return;}}catch(e){reportRpgmError('schedule-window-refresh',e);} runWindowRefresh();}
  // 本地缓存响应可能在新建标题或菜单窗口仍关闭时到达。Window_Base.updateOpen 是
  // 使窗口可渲染的引擎生命周期边界；仅在该转换点刷新可以避免固定延迟，且不会
  // 触碰保存或读取场景。
  function installWindowOpenRefreshHook(){try{if(!window.Window_Base||!Window_Base.prototype.updateOpen||Window_Base.prototype.updateOpen._dsRpgmOpenRefreshHook) return; var oldUpdateOpen=Window_Base.prototype.updateOpen; var updateOpenWrap=function(){var wasOpen=typeof this.isOpen==='function'?this.isOpen():Number(this.openness)>=255; var result=oldUpdateOpen.apply(this,arguments); try{var nowOpen=typeof this.isOpen==='function'?this.isOpen():Number(this.openness)>=255; if(!wasOpen&&nowOpen&&canAutoRefreshWindow(this)&&typeof this.refresh==='function'){var scene=window.SceneManager&&SceneManager._scene; if(!isPersistenceScene(scene)) this.refresh();}}catch(e){reportRpgmError('refresh-window-open-transition',e);} return result;}; updateOpenWrap._dsRpgmOpenRefreshHook=true; updateOpenWrap._dsRpgmOriginal=oldUpdateOpen; Window_Base.prototype.updateOpen=updateOpenWrap;}catch(e){reportRpgmError('install-window-open-refresh-hook',e);}}
  function requestLookup(key){
    if(localLookupPending[key]||pending[key]||messagePagePending[key]||pendingCount>=MAX_PENDING) return; pending[key]=true; pendingCount++; var x=null; var done=false;
    function finish(response,eventName){if(done) return; done=true; x=response; if(pending[key]){delete pending[key]; pendingCount--;} var now=Date.now(); if(x&&x.status===200){try{var r=JSON.parse(x.responseText); var v=r.translated_text||r.translation||key; if(v&&v!==key&&r.source!=='miss'&&r.source!=='queued'&&r.source!=='pass'&&cacheSafeRpgmTranslation(key,v,'single-control-guard')){requestWindowRefresh(); return;}}catch(e){reportRpgmError('parse-translate-response',e);}}else{reportRpgmError('translate-request-'+String(eventName||'http'),new Error('HTTP status '+(x?x.status:'unavailable')));} retryAfter.put(key,now+MISS_RETRY_MS);}
    sendRpgmJson(URL,{text:key},12000,'translate',finish);
  }
  function lookup(s){
    s=String(s==null?'':s); if(!s||hasCjk(s)||isLayoutOnly(s)) return {text:s,hit:true}; var key=keyOf(s); if(!key) return {text:s,hit:true}; var cached=cache.get(key); if(cached) return {text:safeRpgmTranslation(s,cached),hit:true}; var now=Date.now(),retryAt=retryAfter.get(key); if(retryAt&&retryAt>now) return {text:s,hit:false}; if(retryAt) retryAfter.remove(key);
    if(!suppressLookupRequests) requestLookup(key); cached=cache.get(key); if(cached) return {text:safeRpgmTranslation(s,cached),hit:true};
    return {text:s,hit:false};
  }
  function splitRpgmDecor(s){
    s=String(s==null?'':s); var i=0,m; for(;;){var rest=s.slice(i); if((m=/^\\(?:pop|n[1-5]?|nc|nr|nd[1-5]?|ndc|ndr|nt[1-5]?|ntc|ntr)(?:\[[^\]]{0,64}\]|<[^>\n]{0,64}>)/i.exec(rest))){i+=m[0].length; continue;} if((m=/^<[^>\n]{1,64}>/.exec(rest))){i+=m[0].length; continue;} break;}
    if(i<=0||i>=s.length) return null; var body=s.slice(i); if(!/[A-Za-z\u0080-\uffff]/.test(body)) return null; return {prefix:s.slice(0,i),body:body};
  }
  function dataName(kind,id){var t=null,k=String(kind||'').toLowerCase(); if(k==='ii'||k==='ni') t=window.$dataItems; else if(k==='iw'||k==='nw') t=window.$dataWeapons; else if(k==='ia'||k==='na') t=window.$dataArmors; else if(k==='is'||k==='ns') t=window.$dataSkills; else if(k==='it'||k==='nt') t=window.$dataStates; var o=t&&t[parseInt(id,10)]; return o&&o.name?String(o.name):'';}
  function visibleLookupKey(s){
    var changed=false; var text=String(s==null?'':s); text=text.replace(/\\(ii|iw|ia|is|it|ni|nw|na|ns|nt)\[(\d+)\]/gi,function(m,c,id){var n=dataName(c,id); if(n){changed=true; return n;} return m;});
    text=text.replace(/\\v\[(\d+)\]/gi,function(m,id){try{if(window.$gameVariables&&typeof $gameVariables.value==='function'){changed=true; return String($gameVariables.value(Number(id)));}}catch(e){reportRpgmError('resolve-game-variable',e);} return m;});
    text=text.replace(/\\(?:c|i|fs|fr|fb|fi|oc|ow)\[[^\]]{0,64}\]/gi,function(){changed=true; return '';}); text=text.replace(/\\[{}$.|!><^]/g,function(){changed=true; return ' ';}); text=keyOf(text).replace(/[ \t]{2,}/g,' ');
    return changed&&text?text:null;
  }
  var questPrimePending=false;
  var questPrimeSignature='';
  var questPrimeKnown=Object.create(null);
  function primeVisibleQuestText(value){var key=keyOf(value); if(!key||!questPrimeKnown[key]||cache.has(key)||pending[key]||messagePagePending[key]) return; primeMessagePage([key]);}
  function primeGalvQuestCache(){
    if(questPrimePending) return; var qs=window.$gameSystem&&$gameSystem._quests; var list=qs&&qs.quest; if(!list) return; var keys=[],seen=Object.create(null);
    function add(value){if(keys.length>=MAX_QUEST_PRIME||value==null) return; var raw=keyOf(value); if(!raw||raw.length<3||hasCjk(raw)) return; if(!seen[raw]){seen[raw]=true; keys.push(raw);} var visible=visibleLookupKey(raw); if(visible&&!seen[visible]&&keys.length<MAX_QUEST_PRIME){seen[visible]=true; keys.push(visible);}}
    function addArray(values){if(!values||!values.length) return; for(var i=0;i<values.length&&keys.length<MAX_QUEST_PRIME;i++) add(values[i]);}
    for(var i=0;i<list.length&&keys.length<MAX_QUEST_PRIME;i++){var q=list[i]; if(!q) continue; try{var name=typeof q.name==='function'?q.name():q.name; add(name); var split=String(name||'').lastIndexOf(' - '); if(split>=0) add(String(name).slice(split+3));}catch(e){reportRpgmError('read-quest-name',e);} try{addArray(typeof q.objectives==='function'?q.objectives():q.objectives);}catch(e){reportRpgmError('read-quest-objectives',e);} try{addArray(typeof q.desc==='function'?q.desc():q.desc);}catch(e){reportRpgmError('read-quest-description',e);} try{addArray(typeof q.resoTxtArray==='function'?q.resoTxtArray():q.resoTxtArray);}catch(e){reportRpgmError('read-quest-resolution',e);}}
    questPrimeKnown=seen; if(!keys.length) return; var signature=keys.join('\n'); if(signature===questPrimeSignature) return; questPrimePending=true;
    // Galv 全量任务枚举属于后台发现，只能进入 /prefetch。旧本地服务缺少该端点或返回坏 JSON 时，
    // 无法在游戏进程内继续修复；失败只记录诊断并保留原文，不写运行时成功缓存，也不占用可见 /batch 通道。
    var done=false; function finish(response,eventName){if(done) return; done=true; questPrimePending=false; if(response&&response.status===200){try{var r=JSON.parse(response.responseText); if(r&&r.status==='queued'){questPrimeSignature=signature; return;} throw new Error('missing queued prefetch status');}catch(e){reportRpgmError('parse-quest-prefetch-response',e); return;}} reportRpgmError('quest-prefetch-'+String(eventName||'http'),new Error('HTTP status '+(response?response.status:'unavailable')));}
    sendRpgmJson(PREFETCH_URL,{texts:keys},1500,'quest-prefetch',finish);
  }
  function installQuestPrimeHooks(){try{if(window.DataManager&&DataManager.extractSaveContents&&!DataManager.extractSaveContents._dsQuestPrimeHook){var oldExtract=DataManager.extractSaveContents; var wrap=function(){var r=oldExtract.apply(this,arguments); primeGalvQuestCache(); return r;}; wrap._dsQuestPrimeHook=true; DataManager.extractSaveContents=wrap;} if(window.DataManager&&DataManager.setupNewGame&&!DataManager.setupNewGame._dsQuestPrimeHook){var oldSetup=DataManager.setupNewGame; var setupWrap=function(){var r=oldSetup.apply(this,arguments); primeGalvQuestCache(); return r;}; setupWrap._dsQuestPrimeHook=true; DataManager.setupNewGame=setupWrap;} primeGalvQuestCache();}catch(e){reportRpgmError('install-quest-prime-hooks',e);}}
  installQuestPrimeHooks();
  function lookupVisible(orig,prefix,body){var key=visibleLookupKey(body); if(!key||key===keyOf(body)) return null; var r=lookup(key); if(r.hit&&r.text!==key&&r.text!==keyOf(key)) return {text:String(prefix||'')+r.text,hit:true}; if(r.hit) return {text:orig,hit:true}; return {text:orig,hit:false};}
  function lookupDecorated(s){
    var orig=String(s==null?'':s); var raw=lookup(orig); if(raw.hit&&raw.text!==orig&&raw.text!==keyOf(orig)) return raw; var ww=/^(?:<WordWrap>)+/i.exec(orig); if(ww&&ww[0].length<orig.length){var inner=orig.slice(ww[0].length),wrapped=lookup(inner); if(wrapped.hit&&wrapped.text!==inner&&wrapped.text!==keyOf(inner)) return {text:ww[0]+wrapped.text,hit:true}; if(!wrapped.hit) raw.hit=false;} var parts=splitRpgmDecor(orig); if(parts){var body=lookup(parts.body); if(body.hit&&body.text!==parts.body&&body.text!==keyOf(parts.body)) return {text:parts.prefix+body.text,hit:true}; var vis=lookupVisible(orig,parts.prefix,parts.body); if(vis) return vis; if(body.hit&&raw.hit) return {text:orig,hit:true}; return {text:orig,hit:false};} var vis2=lookupVisible(orig,'',orig); if(vis2) return vis2; return raw;
  }
  function tr(s){return lookupDecorated(s).text;}
  var suppressDisplayTranslate=0;
  // 本地缓存查询采用异步方式，渲染器钩子不会阻塞 RPG Maker 帧。有限传输超时
  // 只解除短暂本地门控；未命中和故障仍显示原文，并可继续进入现有前台翻译路径。
  function requestLocalCacheKeys(values,maxKeys){var keys=[],seen=Object.create(null),limit=Number(maxKeys)||64; if(limit<1) limit=64; if(limit>512) limit=512; for(var i=0;i<values.length&&keys.length<limit;i++){var key=keyOf(values[i]); if(!key||cache.has(key)||localLookupState.has(key)||localLookupPending[key]||seen[key]||hasCjk(key)||isLayoutOnly(key)||!/[A-Za-z]/.test(key)) continue; seen[key]=true; localLookupState.put(key,true); localLookupPending[key]=true; keys.push(key);} for(var start=0;start<keys.length;start+=64){(function(batch){var done=false; function finish(response,eventName){if(done) return; done=true; for(var i=0;i<batch.length;i++) delete localLookupPending[batch[i]]; if(response&&response.status===200){try{var r=JSON.parse(response.responseText),hits=r.hits||{}; for(var j=0;j<batch.length;j++){var key=batch[j],value=hits[key]; if(value&&value!==key) cacheSafeRpgmTranslation(key,value,'async-cache-control-guard');}}catch(e){reportRpgmError('parse-async-cache-lookup',e);}}else{reportRpgmError('async-cache-lookup-'+String(eventName||'http'),new Error('HTTP status '+(response?response.status:'unavailable')));} requestWindowRefresh();} sendRpgmJson(CACHE_LOOKUP_URL,{texts:batch},1500,'cache-lookup',finish);})(keys.slice(start,start+64));} return keys.length;}
  function isConvertedRpgmControlToken(part){return part.charCodeAt(0)===27||/^<(?:WordWrap|br\s*\/?)>$/i.test(part);}
  function translateConvertedRpgmText(s,lookupFirst){var orig=String(s==null?'':s); if(orig.indexOf(String.fromCharCode(27))<0){if(lookupFirst){requestLocalCacheKeys([orig],1); primeVisibleQuestText(orig);} return tr(orig);} var parts=orig.split(/(\x1b[A-Za-z]+(?:\[[^\]]{0,64}\]|<[^>\n]{0,64}>)?|\x1b[{}$.|!><^]|<WordWrap>|<br\s*\/?>)/gi),cores=[],allHit=true,changed=false; for(var i=0;i<parts.length;i++){var part=parts[i]; if(!part||isConvertedRpgmControlToken(part)||hasCjk(part)||!/[A-Za-z]/.test(part)) continue; var lead=(part.match(/^\s*/)||[''])[0],tail=(part.match(/\s*$/)||[''])[0],core=part.slice(lead.length,part.length-tail.length); if(core&&/[A-Za-z]/.test(core)) cores.push(core);} if(lookupFirst){requestLocalCacheKeys(cores); for(var ci=0;ci<cores.length;ci++) primeVisibleQuestText(cores[ci]);} for(var j=0;j<parts.length;j++){var value=parts[j]; if(!value||isConvertedRpgmControlToken(value)||hasCjk(value)||!/[A-Za-z]/.test(value)) continue; var prefix=(value.match(/^\s*/)||[''])[0],suffix=(value.match(/\s*$/)||[''])[0],body=value.slice(prefix.length,value.length-suffix.length); if(!body||!/[A-Za-z]/.test(body)) continue; var result=lookupDecorated(body); if(!result.hit) allHit=false; if(result.text!==body){parts[j]=prefix+result.text+suffix; changed=true;}} return allHit&&changed?parts.join(''):orig;}
  function trDisplay(s){return suppressDisplayTranslate>0?String(s==null?'':s):translateConvertedRpgmText(s,true);}
  function withDisplayTranslationSuppressed(fn){suppressDisplayTranslate++; try{return fn();}finally{suppressDisplayTranslate--;}}
  function shouldBitmapTranslate(s){var key=keyOf(s); if(!key||key.length<3||hasCjk(key)) return false; if(!/[A-Za-z]/.test(key)) return false; return true;}
  function trBitmap(s){var orig=String(s==null?'':s); if(suppressDisplayTranslate>0||!shouldBitmapTranslate(orig)) return orig; requestLocalCacheKeys([orig],1); return tr(orig);}
  function finiteDrawWidth(w){w=Number(w); return isFinite(w)&&w>0&&w<1000000;}
  function drawBitmapFit(oldDraw,self,text,x,y,maxWidth,lineHeight,align){var out; try{out=trBitmap(text);}catch(e){reportRpgmError('translate-bitmap-text',e); out=String(text==null?'':text);} if(!finiteDrawWidth(maxWidth)||!hasCjk(out)||!self||typeof self.measureTextWidth!=='function'||typeof self.fontSize!=='number') return oldDraw.call(self,out,x,y,maxWidth,lineHeight,align); var oldSize=self.fontSize; try{var min=Math.max(12,Math.floor(oldSize*0.62)); while(self.fontSize>min&&self.measureTextWidth(out)>maxWidth){self.fontSize--;} return oldDraw.call(self,out,x,y,maxWidth,lineHeight,align);}finally{self.fontSize=oldSize;}}
  function dsTextWidth(win,t){try{if(win&&win.textWidth) return win.textWidth(t); if(win&&win.contents&&win.contents.measureTextWidth) return win.contents.measureTextWidth(t);}catch(e){reportRpgmError('measure-renderer-text',e);} return String(t==null?'':t).length*16;}
  function dsLineHeight(win){try{if(win&&win.techTreeLineHeight) return win.techTreeLineHeight(); if(win&&win.lineHeight) return win.lineHeight();}catch(e){reportRpgmError('read-renderer-line-height',e);} return 36;}
  var rpgmTextExWrapStack=[];
  var rpgmLayoutFallbackCounts=Object.create(null);
  function reportRpgmLayoutFallback(context,detail){if(!rpgmLayoutFallbackCounts) rpgmLayoutFallbackCounts=Object.create(null); var key=String(context||'unknown'),count=(rpgmLayoutFallbackCounts[key]||0)+1; rpgmLayoutFallbackCounts[key]=count; if(count<=3||(count&(count-1))===0){var record={context:key,count:count,detail:String(detail||'')}; var records=window.__deepSeekRpgmDiagnostics||(window.__deepSeekRpgmDiagnostics=[]); records.push(record); while(records.length>32) records.shift(); if(window.console&&typeof console.info==='function') console.info('[DeepSeek RPGM] '+key+' #'+count+': '+record.detail);}}
  function rpgmTextExWidth(win,x,w){var left=Number(x); if(!isFinite(left)) left=0; if(finiteDrawWidth(w)) return Number(w); if(win&&win.contents&&finiteDrawWidth(win.contents.width-left)) return Number(win.contents.width)-left; if(win&&finiteDrawWidth(Number(win.innerWidth)-left)) return Number(win.innerWidth)-left; return 0;}
  function withRpgmTextExWrap(win,text,x,w,translated,draw){var width=rpgmTextExWidth(win,x,w); if(!translated||!hasCjk(text)||!finiteDrawWidth(width)) return draw(); var left=Number(x); if(!isFinite(left)) left=0; var state={win:win,left:left,right:left+width}; rpgmTextExWrapStack.push(state); reportRpgmLayoutFallback('draw-text-ex-auto-wrap','width='+width+', chars='+String(text==null?'':text).length); try{return draw();}finally{rpgmTextExWrapStack.pop();}}
  function currentRpgmTextExWrap(win){for(var i=rpgmTextExWrapStack.length-1;i>=0;i--){if(rpgmTextExWrapStack[i].win===win) return rpgmTextExWrapStack[i];} return null;}
  function rpgmNextWrapUnit(text,index){text=String(text==null?'':text); var unit=text.charAt(index); if(!unit) return ''; var i=index+1; if(/[A-Za-z0-9_'-]/.test(unit)){while(i<text.length&&/[A-Za-z0-9_'-]/.test(text.charAt(i))) unit+=text.charAt(i++);} while(i<text.length&&/[\u3001\u3002\uff0c\uff0e\uff01\uff1f\uff1a\uff1b\uff09\u3011\u300b\u300d\u300f\u2019\u201d\u2026]/.test(text.charAt(i))) unit+=text.charAt(i++); return unit;}
  function installTextExAutoWrapHook(){try{var proto=window.Window_Base&&Window_Base.prototype; if(!proto||typeof proto.processNormalCharacter!=='function'||typeof proto.processNewLine!=='function'||proto.processNormalCharacter._dsRpgmTextExWrapHook) return; var old=proto.processNormalCharacter; var wrap=function(textState){var layout=currentRpgmTextExWrap(this); if(layout&&textState&&typeof textState.index==='number'){var x=Number(textState.x),unit=rpgmNextWrapUnit(textState.text,textState.index); if(unit&&!/\s/.test(unit.charAt(0))&&isFinite(x)&&x>layout.left&&x+dsTextWidth(this,unit)>layout.right){var index=textState.index; this.processNewLine(textState); textState.index=index;}} return old.apply(this,arguments);}; wrap._dsRpgmTextExWrapHook=true; wrap._dsRpgmOriginal=old; proto.processNormalCharacter=wrap;}catch(e){reportRpgmError('install-draw-text-ex-auto-wrap-hook',e);}}
  function drawCjkAutoWrap(win,text,x,y,maxWidth){text=String(text==null?'':text); try{if(win.convertEscapeCharacters) text=win.convertEscapeCharacters(text);}catch(e){reportRpgmError('convert-renderer-escapes',e);} if(!text) return 0; var esc=String.fromCharCode(27); var max=finiteDrawWidth(maxWidth)?Number(maxWidth):1000000; var lh=dsLineHeight(win); var lines=1,x2=0,y2=y; function nl(){lines++; y2+=lh; x2=0;} function drawTok(tok,w){if(x2>0&&x2+w>max) nl(); if(tok===' '&&x2===0) return; win.drawText(tok,x+x2,y2,w,'left'); x2+=w;} for(var i=0;i<text.length;){var rest=text.slice(i); if(text.charAt(i)===esc){var mi=/^\x1bI\[(\d+)\]/.exec(rest); if(mi){var iw=(window.Window_Base&&Window_Base._iconWidth)||32; if(x2>0&&x2+iw>max) nl(); if(win.drawIcon) win.drawIcon(Number(mi[1]),x+x2,y2); x2+=iw; i+=mi[0].length; continue;} var mc=/^\x1bC\[(\d+)\]/.exec(rest); if(mc){if(win.changeTextColor&&win.textColor) win.changeTextColor(win.textColor(Number(mc[1]))); i+=mc[0].length; continue;} if(rest.indexOf(esc+'n')===0){nl(); i+=2; continue;}} var ch=text.charAt(i); if(ch==='\r'||ch==='\n'){if(ch==='\r'&&text.charAt(i+1)==='\n') i++; nl(); i++; continue;} if(/\s/.test(ch)){drawTok(' ',dsTextWidth(win,' ')); i++; continue;} var tok=ch; if(!hasCjk(ch)){var j=i+1; while(j<text.length&&text.charAt(j)!==esc&&!/\s/.test(text.charAt(j))&&!hasCjk(text.charAt(j))) j++; tok=text.slice(i,j); i=j;}else{i++;} drawTok(tok,dsTextWidth(win,tok));} return lines;}
  // 可见消息页批处理负责处理本地 XHR、状态、JSON 和控制令牌故障，因为只有实时
  // RPG Maker 页面规划器知道安全的逐行键。故障继续显示原文，绝不缓存为成功，
  // 同时进入 retryAfter 并输出限频诊断。
  function finishMessagePageBatch(x,batch,eventName){var response=null,results=null,sources=null,translations=null,parsed=false,changed=false,now=Date.now(); if(x&&x.status===200){try{response=JSON.parse(x.responseText); results=response&&response.results; sources=response&&response.sources; translations=response&&response.translations; if(!Array.isArray(results)&&(!translations||typeof translations!=='object')) throw new Error('missing batch result fields'); if(!Array.isArray(results)) results=[]; if(!Array.isArray(sources)) sources=[]; parsed=true;}catch(e){reportRpgmError('parse-message-page-batch-response',e);}}else{reportRpgmError('message-page-batch-'+String(eventName||'http'),new Error('HTTP status '+(x?x.status:'unavailable')));} for(var i=0;i<batch.length;i++){var key=batch[i],value=results&&results[i],source=sources&&sources[i]; delete messagePagePending[key]; if((value==null||value==='')&&translations) value=translations[key]; if(parsed&&value&&value!==key&&source!=='miss'&&source!=='queued'&&source!=='pass'&&cacheSafeRpgmTranslation(key,value,'message-page-control-guard')){changed=true; continue;} retryAfter.put(key,now+MISS_RETRY_MS);} if(changed) requestWindowRefresh();}
  function requestMessagePageBatch(batch){var done=false; function finish(response,eventName){if(done) return; done=true; finishMessagePageBatch(response,batch,eventName);} sendRpgmJson(BATCH_URL,{texts:batch},15000,'message-page-batch',finish);}
  function primeMessagePage(values){var keys=[],seen=Object.create(null),now=Date.now(); for(var i=0;i<values.length&&keys.length<MAX_MESSAGE_PAGE_PRIME;i++){var key=keyOf(values[i]); if(!key||seen[key]||cache.has(key)||pending[key]||messagePagePending[key]||hasCjk(key)||isLayoutOnly(key)||!/[A-Za-z]/.test(key)) continue; var retryAt=retryAfter.get(key); if(retryAt&&retryAt>now) continue; if(retryAt) retryAfter.remove(key); seen[key]=true; messagePagePending[key]=true; keys.push(key);} for(var start=0;start<keys.length;){var batch=[],chars=0; while(start<keys.length&&batch.length<MESSAGE_PAGE_BATCH_MAX){var next=keys[start]; if(batch.length&&chars+next.length>MESSAGE_PAGE_CHAR_BUDGET) break; batch.push(next); chars+=next.length; start++;} requestMessagePageBatch(batch);}}
  function withLookupRequestsSuppressed(fn){suppressLookupRequests++; try{return fn();}finally{suppressLookupRequests--;}}
  function translateTextArray(values,allowPartial,skipLocalLookup){
    if(!values||!values.length) return values; if(!skipLocalLookup) requestLocalCacheKeys(values,512); var out=new Array(values.length); var allHit=true; var changed=false;
    for(var i=0;i<values.length;i++){var orig=String(values[i]==null?'':values[i]); var r=lookupDecorated(orig); out[i]=r.text; if(!r.hit) allHit=false; if(r.text!==orig) changed=true;}
    if(!allHit&&changed&&!allowPartial) return values; return out;
  }
  function planMessagePage(original){var candidates=[],liveCandidates=[]; for(var ci=0;ci<original.length;ci++){var line=original[ci]; candidates.push(line); var unwrapped=line.replace(/^(?:<WordWrap>)+/i,''); if(unwrapped!==line) candidates.push(unwrapped); var decor=splitRpgmDecor(line),body=decor?decor.body:unwrapped; if(body){liveCandidates.push(body); if(body!==line&&body!==unwrapped) candidates.push(body);} var visible=visibleLookupKey(body); if(visible){candidates.push(visible); if(visible!==body) liveCandidates.push(visible);}} var joined=original.join('\n'); return {candidates:candidates,liveCandidates:liveCandidates,joined:joined,large:original.length>24||joined.length>4000};}
  function translateMessageLines(lines,cacheOnly){
    if(!lines||!Array.isArray(lines)||!lines.length) return lines; var original=new Array(lines.length); for(var i=0;i<lines.length;i++) original[i]=String(lines[i]==null?'':lines[i]);
    var plan=planMessagePage(original); if(!cacheOnly) requestLocalCacheKeys(original.length>1?[plan.joined].concat(plan.candidates):plan.candidates,512);
    function resolve(){if(plan.large){if(!cacheOnly) primeMessagePage(plan.liveCandidates); return withLookupRequestsSuppressed(function(){return translateTextArray(original,false,true);});}
      if(!plan.large&&original.length>1){var whole=lookup(plan.joined); if(whole.hit&&whole.text!==plan.joined&&whole.text!==keyOf(plan.joined)) return [whole.text];}
      if(!plan.large&&original.length>1){var first=splitRpgmDecor(original[0]); if(first){var visibleLines=new Array(original.length); visibleLines[0]=visibleLookupKey(first.body)||first.body; for(var vi=1;vi<original.length;vi++){var p=splitRpgmDecor(original[vi]); var b=p?p.body:original[vi]; visibleLines[vi]=visibleLookupKey(b)||b;} var vjoined=visibleLines.join('\n'); var vwhole=lookup(vjoined); if(vwhole.hit&&vwhole.text!==vjoined&&vwhole.text!==keyOf(vjoined)) return [first.prefix+vwhole.text];}}
      return translateTextArray(original,false,true);}
    return cacheOnly?withLookupRequestsSuppressed(resolve):resolve();
  }
  function sameRpgmTextArray(a,b){if(!a||!b||a.length!==b.length) return false; for(var i=0;i<a.length;i++){if(String(a[i]==null?'':a[i])!==String(b[i]==null?'':b[i])) return false;} return true;}
  function messagePageHasLocalLookupPending(lines){var values=new Array(lines.length); for(var i=0;i<lines.length;i++) values[i]=String(lines[i]==null?'':lines[i]); var plan=planMessagePage(values),keys=[plan.joined],seen=Object.create(null); keys=keys.concat(plan.candidates,plan.liveCandidates); for(var j=0;j<keys.length;j++){var key=keyOf(keys[j]); if(!key||seen[key]) continue; seen[key]=true; if(localLookupPending[key]) return true;} return false;}
  // 只有非阻塞 localhost 缓存读取可以短暂推迟页面构建。MZ 会在同步 while 循环中
  // 调用 startMessage，因此延迟启动必须把引擎自有等待计数设为一帧；否则同一次
  // 启动会永久空转并冻结渲染器。远程提供方工作绝不门控消息生命周期。
  // requestLocalCacheKeys 会记录缓存故障或超时、恢复这个已标记启动并保留原文，
  // 且不能创建缓存成功项，因此这个渲染器降级不会隐藏传输错误。
  function deferRpgmMessageForLocalCache(original,translated){return sameRpgmTextArray(original,translated)&&messagePageHasLocalLookupPending(original);}
  function installMessageRuntimeHooks(){
    try{if(window.Game_Message&&Game_Message.prototype.allText&&!Game_Message.prototype.allText._dsRpgmMessageHook){var currentAllText=Game_Message.prototype.allText; var allTextWrap=(function(old){var fn=function(){var original=this&&this._texts; if(original&&Array.isArray(original)&&original.length){try{var translated=translateMessageLines(original); if(translated&&translated!==original) return translated.join('\n');}catch(e){reportRpgmError('translate-message-all-text',e);}} return old.apply(this,arguments);}; fn._dsRpgmMessageHook=true; fn._dsRpgmOriginal=old; return fn;})(currentAllText); Game_Message.prototype.allText=allTextWrap;}}catch(e){reportRpgmError('install-message-all-text-hook',e);}
    try{if(window.Window_Message&&Window_Message.prototype.startMessage&&!Window_Message.prototype.startMessage._dsRpgmMessageHook){var currentStartMessage=Window_Message.prototype.startMessage; var startMessageWrap=(function(old){var fn=function(){this._dsRpgmDeferredMessageStart=false; var gm=window.$gameMessage; var original=gm&&gm._texts; if(!original||!Array.isArray(original)||!original.length) return old.apply(this,arguments); var translated; try{translated=translateMessageLines(original); if(deferRpgmMessageForLocalCache(original,translated)){this._dsRpgmDeferredMessageStart=true; this._waitCount=Math.max(Number(this._waitCount)||0,1); return;}}catch(e){reportRpgmError('translate-message-start',e); return old.apply(this,arguments);} this._dsRpgmRenderedMessageSignature=messageRenderSignature(original,translated); if(sameRpgmTextArray(translated,original)){var sourceResult=old.apply(this,arguments); if(this._textState) scheduleActiveMessageCachePoll(this,original); return sourceResult;} stopActiveMessageCachePoll(this); gm._texts=translated; try{return old.apply(this,arguments);} finally{gm._texts=original;}}; fn._dsRpgmMessageHook=true; fn._dsRpgmOriginal=old; return fn;})(currentStartMessage); Window_Message.prototype.startMessage=startMessageWrap;}}catch(e){reportRpgmError('install-message-start-hook',e);}
  }
  function installTopLevelWindowHooks(){
    try{if(window.Window_Help&&Window_Help.prototype.setText&&!Window_Help.prototype.setText._dsRpgmDisplayHook){var oldHelpSet=Window_Help.prototype.setText; var helpSetTextWrap=function(text){markRpgmDisplayTarget(this,text); var out=text; try{out=trDisplay(text);}catch(e){reportRpgmError('translate-help-text',e);} var rendered=String(out==null?'':out),source=String(text==null?'':text); this._dsRpgmTranslatedCjkText=rendered!==source&&hasCjk(rendered)?rendered:''; return oldHelpSet.call(this,out);}; helpSetTextWrap._dsRpgmDisplayHook=true; helpSetTextWrap._dsRpgmOriginal=oldHelpSet; Window_Help.prototype.setText=helpSetTextWrap;}}catch(e){reportRpgmError('install-help-set-text-hook',e);}
    try{if(window.Game_Message&&Game_Message.prototype.choices&&!Game_Message.prototype.choices._dsRpgmDisplayHook){var oldChoices=Game_Message.prototype.choices; var choicesWrap=function(){var choices=oldChoices.apply(this,arguments); if(choices&&choices.length){try{var translated=translateTextArray(choices); if(translated&&translated!==choices) return translated;}catch(e){reportRpgmError('translate-message-choices',e);}} return choices;}; choicesWrap._dsRpgmDisplayHook=true; choicesWrap._dsRpgmOriginal=oldChoices; Game_Message.prototype.choices=choicesWrap;}}catch(e){reportRpgmError('install-message-choices-hook',e);}
  function applyTranslatedChoiceCommands(win){
    try{var list=win&&win._list; if(!list||!list.length) return; var names=new Array(list.length); for(var i=0;i<list.length;i++) names[i]=list[i]&&list[i].name; var translated=translateTextArray(names); for(var j=0;j<list.length;j++){if(list[j]&&typeof list[j].name==='string') list[j].name=translated[j];}}
    catch(e){reportRpgmError('translate-choice-commands',e);}
  }
    try{if(window.Window_ChoiceList&&Window_ChoiceList.prototype.makeCommandList&&!Window_ChoiceList.prototype.makeCommandList._dsRpgmDisplayHook){var oldChoiceMake=Window_ChoiceList.prototype.makeCommandList; var makeCommandListWrap=function(){var r=oldChoiceMake.apply(this,arguments); applyTranslatedChoiceCommands(this); return r;}; makeCommandListWrap._dsRpgmDisplayHook=true; makeCommandListWrap._dsRpgmOriginal=oldChoiceMake; Window_ChoiceList.prototype.makeCommandList=makeCommandListWrap;}}catch(e){reportRpgmError('install-choice-command-list-hook',e);}
    try{if(window.Window_ChoiceList&&Window_ChoiceList.prototype.maxChoiceWidth&&!Window_ChoiceList.prototype.maxChoiceWidth._dsRpgmDisplayHook){var oldChoiceWidth=Window_ChoiceList.prototype.maxChoiceWidth; var maxChoiceWidthWrap=function(){var w=oldChoiceWidth.apply(this,arguments); try{var gm=window.$gameMessage; var choices=gm&&gm.choices?gm.choices():null; if(choices&&choices.length){var translated=translateTextArray(choices); for(var i=0;i<translated.length;i++){var t=translated[i]; var extra=0; if(this.textWidthEx) extra=this.textWidthEx(t); else if(this.textWidth) extra=this.textWidth(t); else extra=String(t==null?'':t).length; if(this.textPadding) extra+=this.textPadding()*2; if(w<extra) w=extra;}}}catch(e){reportRpgmError('measure-choice-width',e);} return w;}; maxChoiceWidthWrap._dsRpgmDisplayHook=true; maxChoiceWidthWrap._dsRpgmOriginal=oldChoiceWidth; Window_ChoiceList.prototype.maxChoiceWidth=maxChoiceWidthWrap;}}catch(e){reportRpgmError('install-choice-width-hook',e);}
  }
  function installCopiedDrawTextExHooks(){try{if(!window.Window_Base||!Window_Base.prototype._dsDrawTextEx) return; var original=Window_Base.prototype._dsDrawTextEx,count=0; function patch(proto){if(count>=64||!proto||proto===Window_Base.prototype||proto.drawTextEx!==original) return; var wrap=(function(old){var fn=function(text,x,y,w){var self=this; markRpgmDisplayTarget(self,text); var out=text; try{out=translateConvertedRpgmText(text,true);}catch(e){reportRpgmError('translate-copied-draw-text-ex',e);} var changed=String(out==null?'':out)!==String(text==null?'':text); return withRpgmTextExWrap(self,out,x,w,changed,function(){return old.call(self,out,x,y,w);});}; fn._dsRpgmDisplayHook=true; return fn;})(proto.drawTextEx); proto._dsDrawTextEx=proto.drawTextEx; proto.drawTextEx=wrap; count++;} for(var name in window){if(count>=64) break; if(!/^(?:Sprite|Window)_/.test(name)) continue; var ctor=window[name]; patch(ctor&&ctor.prototype);} var types=window.HUDManager&&HUDManager.types; if(types){for(var typeName in types){if(count>=64) break; var entry=types[typeName],registered=entry&&entry.class; patch(registered&&registered.prototype);}}}catch(e){reportRpgmError('install-copied-draw-text-ex-hooks',e);}}
  function installDisplayTextHooks(){
    try{if(window.Bitmap&&Bitmap.prototype.drawText&&!Bitmap.prototype.drawText._dsRpgmDisplayHook){var oldBitmapDraw=Bitmap.prototype.drawText; var bitmapWrap=function(text,x,y,maxWidth,lineHeight,align){markRpgmDisplayTarget(this,text); return drawBitmapFit(oldBitmapDraw,this,text,x,y,maxWidth,lineHeight,align);}; bitmapWrap._dsRpgmDisplayHook=true; Bitmap.prototype._dsBitmapDrawText=oldBitmapDraw; Bitmap.prototype.drawText=bitmapWrap;}}catch(e){reportRpgmError('install-bitmap-draw-hook',e);}
    try{if(window.Window_Base&&Window_Base.prototype.drawTextAutoWrap&&!Window_Base.prototype.drawTextAutoWrap._dsRpgmDisplayHook){var oldAutoWrap=Window_Base.prototype.drawTextAutoWrap; var autoWrap=function(baseText,x,y,maxWidth){var self=this,args=arguments; markRpgmDisplayTarget(self,baseText); var orig,translated; try{orig=String(baseText==null?'':baseText); translated=trDisplay(orig);}catch(e){reportRpgmError('translate-auto-wrap-text',e); return oldAutoWrap.apply(self,args);} if(hasCjk(translated)){try{return withDisplayTranslationSuppressed(function(){return drawCjkAutoWrap(self,translated,x,y,maxWidth);});}catch(e){reportRpgmError('draw-cjk-auto-wrap',e); return withDisplayTranslationSuppressed(function(){return oldAutoWrap.apply(self,args);});}} if(translated!==orig) return withDisplayTranslationSuppressed(function(){return oldAutoWrap.call(self,translated,x,y,maxWidth);}); return withDisplayTranslationSuppressed(function(){return oldAutoWrap.apply(self,args);});}; autoWrap._dsRpgmDisplayHook=true; Window_Base.prototype._dsDrawTextAutoWrap=oldAutoWrap; Window_Base.prototype.drawTextAutoWrap=autoWrap;}}catch(e){reportRpgmError('install-auto-wrap-hook',e);}
    try{if(window.Window_Base&&Window_Base.prototype.drawTextEx&&!Window_Base.prototype.drawTextEx._dsRpgmDisplayHook){var old=Window_Base.prototype.drawTextEx; var drawTextExWrap=function(text,x,y,w){var self=this; markRpgmDisplayTarget(self,text); var out=text; try{out=trDisplay(text);}catch(e){reportRpgmError('translate-draw-text-ex',e);} var rendered=String(out==null?'':out),changed=rendered!==String(text==null?'':text)||self._dsRpgmTranslatedCjkText===rendered; return withRpgmTextExWrap(self,out,x,w,changed,function(){return old.call(self,out,x,y,w);});}; drawTextExWrap._dsRpgmDisplayHook=true; Window_Base.prototype._dsDrawTextEx=old; Window_Base.prototype.drawTextEx=drawTextExWrap;}}catch(e){reportRpgmError('install-draw-text-ex-hook',e);}
    try{if(window.Window_Base&&Window_Base.prototype.drawText&&!Window_Base.prototype.drawText._dsRpgmDisplayHook){var old2=Window_Base.prototype.drawText; var drawTextWrap=function(text,x,y,w,a){markRpgmDisplayTarget(this,text); var out=text; try{out=trDisplay(text);}catch(e){reportRpgmError('translate-draw-text',e);} return old2.call(this,out,x,y,w,a);}; drawTextWrap._dsRpgmDisplayHook=true; Window_Base.prototype._dsDrawText=old2; Window_Base.prototype.drawText=drawTextWrap;}}catch(e){reportRpgmError('install-draw-text-hook',e);}
    installTextExAutoWrapHook();
    installCopiedDrawTextExHooks();
  }
  function installAllRpgmHooks(){installCjkFont(); installQuestPrimeHooks(); installMessageRuntimeHooks(); installTopLevelWindowHooks(); installDisplayTextHooks(); installWindowOpenRefreshHook();}
  // MZ 的 index.html 可能只有 main.js 这个静态脚本，并在本钩子运行后才创建所有
  // rmmz_*/plugins.js 脚本。脚本 load 事件是这些类变为可用的引擎生命周期边界。
  // 监听或安装失败会保留原文并通过 reportRpgmError 记录，绝不产生翻译或缓存成功。
  function isRpgmLifecycleScript(script){var src=String(script&&script.src||'').replace(/\\/g,'/').toLowerCase(); return /(?:^|\/)js\/(?:rmmz_|rpg_|plugins(?:\.js|\/))/.test(src);}
  function attachRpgmLifecycleScriptLoadHook(script){try{if(!script||!script.addEventListener||script._dsRpgmLifecycleLoadHook) return; script.addEventListener('load',function(){try{if(!isRpgmLifecycleScript(script)) return; installPluginLoadHook(); installAllRpgmHooks();}catch(e){reportRpgmError('run-bootstrap-script-load-listener',e);}},false); script._dsRpgmLifecycleLoadHook=true;}catch(e){reportRpgmError('attach-bootstrap-script-load-listener',e);}}
  function installDynamicScriptLoadHook(){try{if(!document||!document.createElement||document.createElement._dsRpgmCreateElementHook) return; var oldCreate=document.createElement; var createWrap=function(){var element=oldCreate.apply(this,arguments); try{if(arguments.length&&String(arguments[0]).toLowerCase()==='script') attachRpgmLifecycleScriptLoadHook(element);}catch(e){reportRpgmError('observe-created-script',e);} return element;}; createWrap._dsRpgmCreateElementHook=true; createWrap._dsRpgmOriginal=oldCreate; document.createElement=createWrap;}catch(e){reportRpgmError('install-dynamic-script-load-hook',e);}}
  // plugins.js 可能在本钩子运行前创建全部插件标签。只有 DOM load 生命周期能判断
  // 外部脚本何时完成对引擎方法的替换；附加失败会继续显示原文，不创建缓存成功项，
  // 并由 reportRpgmError 记录。
  function attachPluginScriptLoadHook(script){try{if(!script||!script.addEventListener||script._dsRpgmLoadHook) return; var src=String(script.src||'').replace(/\\/g,'/').toLowerCase(); if(src&&src.indexOf('js/plugins/')<0) return; script.addEventListener('load',installAllRpgmHooks,false); script._dsRpgmLoadHook=true;}catch(e){reportRpgmError('attach-plugin-load-listener',e);}}
  function installPluginLoadHook(){try{var scripts=document&&document.getElementsByTagName?document.getElementsByTagName('script'):null; if(scripts){for(var i=0;i<scripts.length;i++) attachPluginScriptLoadHook(scripts[i]);} if(!window.PluginManager||!PluginManager.loadScript||PluginManager.loadScript._dsRpgmPluginLoadHook) return; var oldLoadScript=PluginManager.loadScript; var loadScriptWrap=function(){var r=oldLoadScript.apply(this,arguments); try{var current=document.getElementsByTagName('script'),script=current&&current[current.length-1]; attachPluginScriptLoadHook(script);}catch(e){reportRpgmError('observe-plugin-load-script',e);} return r;}; loadScriptWrap._dsRpgmPluginLoadHook=true; loadScriptWrap._dsRpgmOriginal=oldLoadScript; PluginManager.loadScript=loadScriptWrap;}catch(e){reportRpgmError('install-plugin-load-hook',e);}}
  installDynamicScriptLoadHook();
  installPluginLoadHook();
  installAllRpgmHooks();
})();
