param(
    [Parameter(Mandatory = $true)]
    [string]$Path
)

$ErrorActionPreference = "Stop"

$target = Resolve-Path -LiteralPath $Path
$root = $target.Path
$tempRoot = $null

if ((Get-Item -LiteralPath $root).PSIsContainer -eq $false) {
    if ([System.IO.Path]::GetExtension($root).ToLowerInvariant() -ne ".zip") {
        throw "Audit target must be a directory or .zip archive: $root"
    }
    $repo = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
    $tempRoot = Join-Path $repo ("build\open_source\_audit_" + [Guid]::NewGuid().ToString("N"))
    New-Item -ItemType Directory -Path $tempRoot | Out-Null
    Expand-Archive -LiteralPath $root -DestinationPath $tempRoot -Force
    $root = $tempRoot
}

try {
    $forbiddenExtensions = @(
        ".dll", ".exe", ".pdb", ".mdb", ".otf", ".ttf", ".ttc", ".woff",
        ".woff2", ".zip", ".7z", ".rar", ".tar", ".gz", ".tsv", ".log",
        ".ini"
    )

    $forbiddenDirNames = @(
        "artifacts",
        "logs",
        "toolchain",
        "UnityManagedRefs",
        "UnityInteropRefs",
        "BepInExRuntime",
        "UnityMonoRuntime",
        "UnityMonoRuntime6",
        "XUnityAutoTranslator",
        "TMPFontAssetBundles",
        "TranslationCache"
    )

    $forbiddenFileNamePatterns = @(
        "^api\.ini$",
        "^launcher\.ini$",
        "^translation_memory.*",
        "^_AutoGeneratedTranslations\.txt$",
        "^LogOutput\.log$"
    )

    $contentPatterns = @(
        "sk-[A-Za-z0-9]{16,}",
        "(?i)api[_-]?key\s*=\s*[^<\s][^\r\n]+",
        "(?i)password\s*=\s*[^<\s][^\r\n]+",
        "(?i)secret\s*=\s*[^<\s][^\r\n]+",
        "(?i)Authorization:\s*Bearer\s+[A-Za-z0-9._-]+",
        "C:\\Users\\[A-Za-z0-9._-]+",
        "E:\\Projects\\[^\\\r\n]+",
        "/Users/[A-Za-z0-9._-]+",
        "/home/[A-Za-z0-9._-]+",
        ("Inner" + "Self"),
        ("Blood" + "crave"),
        ("Third" + " Crisis"),
        ("The Glowing" + " Hole"),
        ("Young, smart," + " healthy")
    )

    $errors = [System.Collections.Generic.List[string]]::new()

    Get-ChildItem -LiteralPath $root -Recurse -Directory | ForEach-Object {
        if ($forbiddenDirNames -contains $_.Name) {
            [void]$errors.Add("Forbidden directory: $($_.FullName)")
        }
    }

    $files = Get-ChildItem -LiteralPath $root -Recurse -File
    foreach ($file in $files) {
        $ext = $file.Extension.ToLowerInvariant()
        if ($forbiddenExtensions -contains $ext) {
            [void]$errors.Add("Forbidden file extension: $($file.FullName)")
        }
        foreach ($pattern in $forbiddenFileNamePatterns) {
            if ($file.Name -match $pattern) {
                [void]$errors.Add("Forbidden file name: $($file.FullName)")
                break
            }
        }
        try {
            $text = Get-Content -LiteralPath $file.FullName -Raw -ErrorAction Stop
        } catch {
            [void]$errors.Add("Unreadable or non-text file: $($file.FullName)")
            continue
        }
        foreach ($pattern in $contentPatterns) {
            if ($text -match $pattern) {
                [void]$errors.Add("Forbidden content pattern '$pattern' in $($file.FullName)")
                break
            }
        }
    }

    if ($errors.Count -gt 0) {
        $preview = ($errors | Select-Object -First 80) -join "`n"
        throw "Open-source release audit failed:`n$preview"
    }

    Write-Host "Open-source release audit passed: $root"
} finally {
    if ($tempRoot -and (Test-Path -LiteralPath $tempRoot)) {
        $resolvedTemp = (Resolve-Path -LiteralPath $tempRoot).Path
        $repoBuild = (Resolve-Path (Join-Path $PSScriptRoot "..\build\open_source")).Path
        if ($resolvedTemp.StartsWith($repoBuild, [System.StringComparison]::OrdinalIgnoreCase)) {
            Remove-Item -LiteralPath $resolvedTemp -Recurse -Force
        }
    }
}
